// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxm00HiyZNubB7Oim81WFVZ1SZeq5gorc',
    appId: '1:912403953924:web:a45d0d94a5704ebc62b851',
    messagingSenderId: '912403953924',
    projectId: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod',
    authDomain: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod.firebaseapp.com',
    storageBucket: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFdmwts1kUrv2-AtSk-4hT4a5nK_bxN0',
    appId: '1:912403953924:android:130f151470d0e22862b851',
    messagingSenderId: '912403953924',
    projectId: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod',
    storageBucket: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Pgol3oFXW9s9-1GpIVZc5dIuhNB72qU',
    appId: '1:912403953924:ios:8175741bb9ae324562b851',
    messagingSenderId: '912403953924',
    projectId: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod',
    storageBucket: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod.appspot.com',
    iosBundleId: 'com.example.ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpodFlutterRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Pgol3oFXW9s9-1GpIVZc5dIuhNB72qU',
    appId: '1:912403953924:ios:8175741bb9ae324562b851',
    messagingSenderId: '912403953924',
    projectId: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod',
    storageBucket: 'ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpod-flutter-riverpod.appspot.com',
    iosBundleId: 'com.example.ulearning_flutter_riverpod_flutter_riverpod_flutter_riverpodFlutterRiverpod',
  );
}
